# Build

name: Build

on:
  push:
    branches: ['main']


env:
  NAME: OS


jobs:

  # Build Job
  build:
    name: Build Job
    runs-on: ubuntu-latest

    # Start with a fresh Ubuntu container
    container:
      image: ubuntu:22.04
      options: --privileged --device=/dev/loop-control


    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check
        run: |
          
          ls -lh /




