#file: noinspection SpellCheckingInspection

name: Build

on:
  push:
    branches: ['main']


env:
  NAME: OS
  BUILD_DIR: /workspace/build


jobs:

  # Build Job
  build:
    name: Build Job
    runs-on: ubuntu-latest

    # Start with a fresh Ubuntu container
    container:
      image: ubuntu:22.04
      options: --privileged --device=/dev/loop-control


    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update         
          apt-get install -y xorriso isolinux syslinux-utils
          
          




